### ISSUE TITLE
Public release of pre-trained models

### ISSUE THREAD

**Issue by JmGarzon** [poloclub/unitable#1]
Hello! Thank you for your incredible work. We're interested in replicating your results. Are you planning to release the pre-trained model weights?

**Comment by ShengYun-Peng** [comment]
> Hello! Thank you for your incredible work. We're interested in replicating your results. Are you planning to release the pre-trained model weights?

Yes! They will be released in a few weeks.

**Comment by Filimoa** [comment]
Seconded!

**Comment by ShengYun-Peng** [comment]
Thank you all for your patience! The pretrained and finetuned model weights are publicly available now! Please follow the instructions in the README.md to run the training and inference code.
