### ISSUE TITLE
Incorrect table strcuture detection and text extraction

### ISSUE THREAD

**Issue by vikas-singh16** [poloclub/unitable#10]
Hi, 
I am having an input image of size (338, 1388, 3). This is the input image.
![Airmaster_20892_Specification_Sheet_1tb_0](https://github.com/poloclub/unitable/assets/56232023/8ba51563-994b-4e01-bdcd-7a009b0ec687).

This is the table structure model output.
![Screenshot from 2024-05-31 10-50-06](https://github.com/poloclub/unitable/assets/56232023/9948a247-8943-46a7-bc2d-64d594214371).

This is the cell detection model output.
![Screenshot from 2024-05-31 10-51-10](https://github.com/poloclub/unitable/assets/56232023/147b289d-c875-446d-94f9-1224d0fedb50)

This is the final output in a dataframe.
![Screenshot from 2024-05-31 10-52-01](https://github.com/poloclub/unitable/assets/56232023/996d5a21-16bd-4c4c-8d5d-2a912a08e0c0).

I have few question regarding this.
1. why is the table structure misaligned?
2. Is the a way i can input an image greater than (448 X 448) size. As i believe that this output is due to the resizing of the image into (448 X 448) size.
3. Is there any way, these models can run on cpu?

**Comment by ShengYun-Peng** [comment]
Hi @vikas-singh16, thanks for your interest!

1. The table in the screenshot seems OOD of the training distribution as it has super bold boundaries. I suggest finetuning on your customized dataset for better performance. 
2. It's possible but that will also trigger finetuning. 
3. You can directly run the full pipeline notebook on cpu by toggling the device variable.

**Comment by vikas-singh16** [comment]
Hi, Thanks for the response. I tried a small hack and it worked. Just resize the while maintaining the image aspect ratios. The image will something like this. 

Input Image
![padded_2_Airmaster_20892_Specification_Sheet_1tb_0](https://github.com/poloclub/unitable/assets/56232023/8090c6de-d1c6-4b7e-9384-33c011d91dd1)

Output 
![Screenshot from 2024-06-10 10-51-07](https://github.com/poloclub/unitable/assets/56232023/4344b0b0-36ac-4a84-9f8f-45c802a0c38b)

Pls let me know your thought on this.

**Comment by vikas-singh16** [comment]
hi, Now with this approach I have encountered another issue. The table Headers are not properly placed at the right spot. While exploring this issue, I can across a function named "build_table_from_html_and_cell". Pls can u briefly explain me how are to connecting the html output and cell output and combining them into one.

**Comment by yumikim381** [comment]
Does preserving aspect ratio works better for you in your use cases? I m guessing it works better for non-square like tables

**Comment by vikas-singh16** [comment]
yes, It does work better in my case.
