### ISSUE TITLE
Dataset loading error

### ISSUE THREAD

**Issue by lerndeep** [poloclub/unitable#12]
@polochau 
when I try to train unitable using large dataset synthtabnet and pubnet I got error on dataset json file.
I hope you make data cleaning and remove those issue.
![image](https://github.com/poloclub/unitable/assets/55526377/1b6cbcbc-1531-4ac6-9343-9a0bc38f87e1)

 could you please share that python file or label json file ?

**Comment by ShengYun-Peng** [comment]
Hi, the annotation error above was from the original SynthTabNet dataset. You can reformat it based on our dataset annotation instructions [here](https://github.com/poloclub/unitable?tab=readme-ov-file#dataset-annotation-format).
