### ISSUE TITLE
Evaluation process

### ISSUE THREAD

**Issue by lerndeep** [poloclub/unitable#13]
@polochau 

I want to evaluate this for custom dataset.
But there is no evaluation file to measure metrix. 
can you explain me how can I measure?

**Comment by ShengYun-Peng** [comment]
Hi, the S-TEDS and TEDS can be evaluated with [the metric here](https://github.com/poloclub/unitable/blob/main/src/utils/teds.py). COCO mAP can be measured [here](https://github.com/poloclub/unitable/blob/main/src/utils/coco_map.py).
