### ISSUE TITLE
The problem of Chinse table 

### ISSUE THREAD

**Issue by lihuikenny** [poloclub/unitable#26]
Using the pre-trained model to identify Chinese tables, the effect is very poor and the characters are garbled. Is it because the data sets of the pre-trained model are all in English?
![image](https://github.com/user-attachments/assets/6f2a83bd-d91a-4dd2-90e4-855e31c8478c)
![image](https://github.com/user-attachments/assets/12aa20aa-1680-4315-b8db-aa586d313dd0)

**Comment by lihuikenny** [comment]
anyone help me?

**Comment by gjgjh** [comment]
I believe the traning data used in pretrained model was in English only. However, the table structure in your result seems good and you can use other OCR methods (such as PaddleOCR) instead.

**Comment by ShengYun-Peng** [comment]
Thank you both! Yes, @gjgjh is correct. All training datasets are English-based, and you can simply replace the OCR branch to digitalize your table in different languages.
