### ISSUE TITLE
Infer result is too bad

### ISSUE THREAD

**Issue by Number18-tong** [poloclub/unitable#27]
The display video shows that unitable can parse complicated table correctly, I try to infer the image as bellow, and get the result as bellow, the result is too bad, and I want to know if the model can handle the complicated table image ?
![企业微信截图_96c68bcc-a89b-4e08-b2af-aaeeab03ab65](https://github.com/user-attachments/assets/97a00487-417e-4f6a-8822-0080d8be1702)

![企业微信截图_17248977057787](https://github.com/user-attachments/assets/ce018f68-4ae0-475a-8be2-29deabbd0e59)

**Comment by ShengYun-Peng** [comment]
Thanks! If you take a closer look, you can tell the main structure is correct, but the OCR is off. It's mainly because most of the cell contents in the publicly available training dataset are too blurry and have low image resolution. We may consider retrain the OCR branch in the near future.
