### ISSUE TITLE
No model file in experiments dir post pretraining

### ISSUE THREAD

**Issue by xuzmocode4-325** [poloclub/unitable#32]
After vqvae pretraining, the newly created directory for the experiment had no model file. There are some new objects with the name structure of "core [dot] xxx" (for example "core.524"). 

Could someone please explain what to do with these files, if they are useful, or what they represent?  I am also asking for advice on what next steps to follow to produce a custom model file that can be used in the inference notebook. I am grateful for any help you can provide.

**Comment by ShengYun-Peng** [comment]
Thanks! This never happened to me during training. The model weights are saved here in the trainer: https://github.com/poloclub/unitable/blob/af1163af653e0364843fd56e1eeeb378160c2a40/src/trainer/train_vqvae.py#L230. Please double-check your config file whether you have forbidden the saving.
