### ISSUE TITLE
Finetuning not using any ssp pretrain weight

### ISSUE THREAD

**Issue by lerndeep** [poloclub/unitable#9]
@polochau 
I check your main.py file but when i try to train fine-tuning there is no pretrain weight loading.
elif model_name == "EncoderDecoder":
        max_seq_len = max(
            (cfg.trainer.img_size[0] // cfg.model.backbone_downsampling_factor)
            * (cfg.trainer.img_size[1] // cfg.model.backbone_downsampling_factor),
            cfg.trainer.max_seq_len,
        )  # for positional embedding
        model = instantiate(
            cfg.model.model,
            max_seq_len=max_seq_len,
            vocab_size=vocab.get_vocab_size(),
            padding_idx=vocab.token_to_id("<pad>"),
        )
could you please check this?

**Comment by ShengYun-Peng** [comment]
Thanks for your interest! The pretrained model weight is [loaded in the trainer](https://github.com/poloclub/unitable/blob/af1163af653e0364843fd56e1eeeb378160c2a40/src/trainer/train_table.py#L94).

**Comment by lerndeep** [comment]
@polochau  
Thank you for your response.
But when I tried to load weights I got error message
![image](https://github.com/poloclub/unitable/assets/55526377/3d06198c-840e-4241-b6d1-0480698e7649)
Could you please let me know how to solve?

**Comment by lerndeep** [comment]
When I tried to finetune large module I got error 
![image](https://github.com/poloclub/unitable/assets/55526377/b622f1be-324f-4db4-954a-b74df0eb1f4b)
How can I train large module by increasing max_seq_len=2048 from 1024?

If I want to train with higher max_seq_len it is compulsory to train pretrain and fine-tuning?
Please help me
